define(
  ['text!spec/xdots/directed/abstract.xdot',
  'text!spec/xdots/directed/alf.xdot',
  'text!spec/xdots/directed/arr_none.xdot',
  'text!spec/xdots/directed/arrows.xdot',
  'text!spec/xdots/directed/awilliams.xdot',
  'text!spec/xdots/directed/biological.xdot',
  'text!spec/xdots/directed/clust.xdot',
  'text!spec/xdots/directed/clust1.xdot',
  'text!spec/xdots/directed/clust2.xdot',
  'text!spec/xdots/directed/clust3.xdot',
  'text!spec/xdots/directed/clust4.xdot',
  'text!spec/xdots/directed/clust5.xdot',
  'text!spec/xdots/directed/crazy.xdot',
  'text!spec/xdots/directed/ctext.xdot',
  'text!spec/xdots/directed/dfa.xdot',
  'text!spec/xdots/directed/fig6.xdot',
  'text!spec/xdots/directed/fsm.xdot',
  'text!spec/xdots/directed/grammar.xdot',
  'text!spec/xdots/directed/hashtable.xdot',
//  'text!spec/xdots/directed/honda-tokoro.xdot',
//  'text!spec/xdots/directed/japanese.xdot',
  'text!spec/xdots/directed/jcctree.xdot',
  'text!spec/xdots/directed/jsort.xdot',
  'text!spec/xdots/directed/KW91.xdot',
//  'text!spec/xdots/directed/Latin1.xdot',
  'text!spec/xdots/directed/ldbxtried.xdot',
  'text!spec/xdots/directed/longflat.xdot',
  'text!spec/xdots/directed/mike.xdot',
  'text!spec/xdots/directed/NaN.xdot',
  'text!spec/xdots/directed/nhg.xdot',
//  'text!spec/xdots/directed/oldarrows.xdot',
  'text!spec/xdots/directed/pgram.xdot',
//  'text!spec/xdots/directed/pm2way.xdot',
//  'text!spec/xdots/directed/pmpipe.xdot',
  'text!spec/xdots/directed/polypoly.xdot',
//  'text!spec/xdots/directed/proc3d.xdot',
  'text!spec/xdots/directed/psfonttest.xdot',
  'text!spec/xdots/directed/record2.xdot',
  'text!spec/xdots/directed/records.xdot',
  'text!spec/xdots/directed/rowe.xdot',
//  'text!spec/xdots/directed/russian.xdot',
  'text!spec/xdots/directed/sdh.xdot',
  'text!spec/xdots/directed/shells.xdot',
//  'text!spec/xdots/directed/states.xdot',
  'text!spec/xdots/directed/structs.xdot',
  'text!spec/xdots/directed/switch.xdot',
  'text!spec/xdots/directed/table.xdot',
  'text!spec/xdots/directed/train11.xdot',
  'text!spec/xdots/directed/trapeziumlr.xdot',
  'text!spec/xdots/directed/tree.xdot',
  'text!spec/xdots/directed/triedds.xdot',
  'text!spec/xdots/directed/try.xdot',
  'text!spec/xdots/directed/unix.xdot',
  'text!spec/xdots/directed/unix2.xdot',
  'text!spec/xdots/directed/viewfile.xdot',
  'text!spec/xdots/directed/world.xdot'], function () {
  return [].slice.call(arguments);
});