define(
  ['text!dots/directed/abstract.gv',
  'text!dots/directed/alf.gv',
  'text!dots/directed/arr_none.gv',
  'text!dots/directed/arrows.gv',
  'text!dots/directed/awilliams.gv',
  'text!dots/directed/biological.gv',
  'text!dots/directed/clust.gv',
  'text!dots/directed/clust1.gv',
  'text!dots/directed/clust2.gv',
  'text!dots/directed/clust3.gv',
  'text!dots/directed/clust4.gv',
  'text!dots/directed/clust5.gv',
  'text!dots/directed/crazy.gv',
  'text!dots/directed/ctext.gv',
  'text!dots/directed/dfa.gv',
  'text!dots/directed/fig6.gv',
  'text!dots/directed/fsm.gv',
  'text!dots/directed/grammar.gv',
  'text!dots/directed/hashtable.gv',
//  'text!dots/directed/honda-tokoro.gv',
  'text!dots/directed/japanese.gv',
  'text!dots/directed/jcctree.gv',
  'text!dots/directed/jsort.gv',
  'text!dots/directed/KW91.gv',
//  'text!dots/directed/Latin1.gv',
  'text!dots/directed/ldbxtried.gv',
  'text!dots/directed/longflat.gv',
  'text!dots/directed/mike.gv',
  'text!dots/directed/NaN.gv',
  'text!dots/directed/nhg.gv',
//  'text!dots/directed/oldarrows.gv',
  'text!dots/directed/pgram.gv',
//  'text!dots/directed/pm2way.gv',
//  'text!dots/directed/pmpipe.gv',
  'text!dots/directed/polypoly.gv',
//  'text!dots/directed/proc3d.gv',
  'text!dots/directed/psfonttest.gv',
  'text!dots/directed/record2.gv',
  'text!dots/directed/records.gv',
  'text!dots/directed/rowe.gv',
//  'text!dots/directed/russian.gv',
  'text!dots/directed/sdh.gv',
  'text!dots/directed/shells.gv',
//  'text!dots/directed/states.gv',
  'text!dots/directed/structs.gv',
  'text!dots/directed/switch.gv',
  'text!dots/directed/table.gv',
  'text!dots/directed/train11.gv',
  'text!dots/directed/trapeziumlr.gv',
  'text!dots/directed/tree.gv',
  'text!dots/directed/triedds.gv',
  'text!dots/directed/try.gv',
  'text!dots/directed/unix.gv',
  'text!dots/directed/unix2.gv',
  'text!dots/directed/viewfile.gv',
  'text!dots/directed/world.gv'], function () {
  return [].slice.call(arguments);
});